config:
  aws:region: us-east-2
  overlayer:sqsVisibilityTimeoutSeconds: "300"
  overlayer:dlqMessageRetentionSeconds: "1209600"
  overlayer:ffmpegMinBitrate: "3000"
  overlayer:ffmpegMaxBitrate: "6500"
  overlayer:alertEmail: sousjonathan@gmail.com
  overlayer:corsAllowedOrigin: "https://overlayer-dev.jonsousa.dev"
  overlayer:acmCertificateArn: "arn:aws:acm:us-east-1:459632521199:certificate/a0edcf30-651a-4784-8097-7e23ec720a56"
encryptionsalt: v1:xF4DzkwcJu4=:v1:X+Ae5O+HydhxHIgi:h6NIFuY7PgAnxHwKRHHhXnpxEWhLLQ==
