config:
  aws:region: us-east-2
  overlayer:sqsVisibilityTimeoutSeconds: "300"
  overlayer:dlqMessageRetentionSeconds: "1209600"
  overlayer:ffmpegMinBitrate: "3000"
  overlayer:ffmpegMaxBitrate: "6500"
encryptionsalt: v1:qgORON0cGPQ=:v1:7eKWFYAs7k0m1cpL:phd7xEVdiDb+Qm6oM+B1XQ6kZ3cPYw==
